print('Replika:Hey,How\'s your day going?')
input('Enter your response here:')
print('Replika:I am also doing fine.Thank you')
input('Enter your response here:')
print('Replika:Would you care to hear a joke? ')
input('Enter your response here:')
print('Replika:Do you know what the word programmer actually means?')
input('Enter your response here:')
print('Replika:It\'s actually a person who fixes a problem you didn\'t know you had,in a way you don\'t understand.')
input('Enter your response here:')
print('hahahahaha'*100)