name=input('Full name:')
id=input('Your ID:')
Semester=input('Your Semester:')
Hobby=input('Your Hobby:')
movie=input('Your favourite movie:')
print('Full name:{}\n Your ID:{}\n Your Semester{}\n Your Hobby:{}\n Your favourite movie:{}'.format(name,id,Semester,Hobby,movie))